import { Inter } from "next/font/google";
import "../globals.css";
import Navigation from "@/components/Navigation";
import dynamic from 'next/dynamic';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const DynamicNavigation = dynamic(() => import('@/components/Navigation'), { ssr: false });


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DynamicNavigation/>
      <body className="bg-white">{children}</body>
    </html>
  );
}